export interface SeoPageConfig {
  category: 'community' | 'guide' | 'tools' | 'challenge'
  slug: string
  title: string
  h1: string
  description: string
  keywords: string[]
  toneHint: string
  relatedSlugs: string[]
}

export const seoPages: SeoPageConfig[] = [
  // ── COMMUNITY ──────────────────────────────────────────────────────────────
  {
    category: 'community',
    slug: 'founder-community-india',
    title: 'Best Founder Community in India 2025',
    h1: 'Find Your Founder Community in India',
    description: 'Looking for a founder community in India? Founders Wing is where aspiring entrepreneurs stop overthinking and start building real businesses with AI.',
    keywords: ['founder community india', 'founder community', 'entrepreneur community india'],
    toneHint: 'warm, motivating, India-focused, action-oriented',
    relatedSlugs: ['entrepreneur-community-india', 'ai-founder-community', 'paid-founder-community-india'],
  },
  {
    category: 'community',
    slug: 'entrepreneur-community-india',
    title: 'Best Entrepreneur Community in India 2025',
    h1: 'Join India\'s Most Action-Oriented Entrepreneur Community',
    description: 'Tired of free communities full of lurkers? Founders Wing is a paid entrepreneur community in India where members actually build, ship, and earn.',
    keywords: ['entrepreneur community india', 'entrepreneur community', 'startup community india'],
    toneHint: 'bold, differentiated, anti-lurker, India-focused',
    relatedSlugs: ['founder-community-india', 'paid-founder-community-india', 'accountability-community-for-founders'],
  },
  {
    category: 'community',
    slug: 'ai-founder-community',
    title: 'AI Founder Community India — Build Faster with AI',
    h1: 'The AI Founder Community Built for Action-Takers',
    description: 'Founders Wing is India\'s leading AI founder community. Get weekly AI tool breakdowns, playbooks, and a cohort of founders using AI to launch real businesses.',
    keywords: ['ai founder community', 'ai startup community india', 'ai entrepreneur community'],
    toneHint: 'tech-savvy, exciting, forward-looking, practical',
    relatedSlugs: ['ai-startup-community-india', 'ai-tools-for-founders-india', 'founder-community-india'],
  },
  {
    category: 'community',
    slug: 'startup-community-india',
    title: 'Startup Community India — For Aspiring Founders',
    h1: 'India\'s Startup Community for First-Time Founders',
    description: 'Find your startup tribe in India. Founders Wing connects aspiring entrepreneurs, provides AI tools, accountability, and weekly sessions to help you launch faster.',
    keywords: ['startup community india', 'startup community', 'india startup ecosystem'],
    toneHint: 'inclusive, beginner-friendly, community-driven, India-focused',
    relatedSlugs: ['founder-community-india', 'founder-community-for-beginners', 'entrepreneur-community-india'],
  },
  {
    category: 'community',
    slug: 'online-business-community-india',
    title: 'Online Business Community India — Stop Lurking, Start Building',
    h1: 'Join India\'s Best Online Business Community',
    description: 'Founders Wing is the online business community in India where members build real income streams. Weekly AI tool drops, sprints, and accountability — from ₹5,999.',
    keywords: ['online business community india', 'online business community', 'make money online india community'],
    toneHint: 'practical, income-focused, action-oriented, India-specific',
    relatedSlugs: ['founder-community-india', 'first-10k-challenge-india', 'how-to-make-first-money-online-india'],
  },
  {
    category: 'community',
    slug: 'accountability-community-for-founders',
    title: 'Accountability Community for Founders India',
    h1: 'An Accountability Community That Actually Holds You to Your Goals',
    description: 'Stop setting goals alone. Founders Wing pairs you with an accountability buddy and a sprint cohort so you finally follow through on your business ideas.',
    keywords: ['accountability community founders', 'accountability partner founder india', 'founder accountability'],
    toneHint: 'empathetic, problem-aware, solution-focused',
    relatedSlugs: ['founder-community-india', 'founder-accountability-challenge', 'how-to-build-accountability-as-a-founder'],
  },
  {
    category: 'community',
    slug: 'whatsapp-community-for-entrepreneurs',
    title: 'Best WhatsApp Community for Entrepreneurs India 2025',
    h1: 'Beyond WhatsApp: A Real Community for Entrepreneurs',
    description: 'Free WhatsApp groups have 5,000+ members and zero signal. Founders Wing is a focused, paid community where every member is building something real.',
    keywords: ['whatsapp community entrepreneurs india', 'entrepreneur whatsapp group india', 'best whatsapp group for entrepreneurs'],
    toneHint: 'contrarian, honest, upgrade-focused, India-aware',
    relatedSlugs: ['paid-founder-community-india', 'entrepreneur-community-india', 'founder-community-india'],
  },
  {
    category: 'community',
    slug: 'founder-community-for-beginners',
    title: 'Founder Community for Beginners India — No Experience Needed',
    h1: 'A Founder Community That Welcomes Complete Beginners',
    description: 'Never built a business before? That\'s exactly who Founders Wing is for. Our community welcomes beginners with ideas but zero clue — and turns them into builders.',
    keywords: ['founder community beginners', 'entrepreneur community for beginners india', 'how to join founder community india'],
    toneHint: 'welcoming, reassuring, beginner-affirming, zero-judgment',
    relatedSlugs: ['founder-community-india', 'how-to-stop-overthinking-and-start-building', 'aspiring-entrepreneur-guide-india'],
  },
  {
    category: 'community',
    slug: 'paid-founder-community-india',
    title: 'Paid Founder Community India — Why It\'s Worth It',
    h1: 'Why a Paid Founder Community Gets Better Results Than Free Groups',
    description: 'Free communities attract lurkers. Paid communities attract doers. Founders Wing is India\'s premier paid founder community starting at just ₹5,999 for 6 months.',
    keywords: ['paid founder community india', 'paid entrepreneur community india', 'founder community membership india'],
    toneHint: 'confident, value-justifying, ROI-focused',
    relatedSlugs: ['founder-community-india', 'whatsapp-community-for-entrepreneurs', 'entrepreneur-community-india'],
  },
  {
    category: 'community',
    slug: 'ai-startup-community-india',
    title: 'AI Startup Community India — Build with AI Tools',
    h1: 'India\'s AI Startup Community: Learn, Build, and Launch Together',
    description: 'Founders Wing is where India\'s next AI startups are being born. Weekly AI tool drops, sprint challenges, and a community of founders building with AI daily.',
    keywords: ['ai startup community india', 'ai startup india', 'artificial intelligence entrepreneur community india'],
    toneHint: 'tech-forward, ambitious, India-proud',
    relatedSlugs: ['ai-founder-community', 'ai-tools-for-founders-india', 'best-ai-tools-for-entrepreneurs-2025'],
  },

  // ── GUIDE ──────────────────────────────────────────────────────────────────
  {
    category: 'guide',
    slug: 'how-to-make-first-money-online-india',
    title: 'How to Make Your First Money Online in India (2025 Guide)',
    h1: 'How to Make Your First Money Online in India',
    description: 'A practical guide for aspiring entrepreneurs in India to make their first income online — using AI tools, proven business models, and an action-first approach.',
    keywords: ['how to make first money online india', 'earn money online india', 'make money online india for beginners'],
    toneHint: 'practical, step-by-step, encouraging, India-specific with rupee amounts',
    relatedSlugs: ['first-10k-online-india', 'online-business-ideas-india-2025', 'how-to-start-online-business-india'],
  },
  {
    category: 'guide',
    slug: 'how-to-start-online-business-india',
    title: 'How to Start an Online Business in India (Beginner\'s Guide 2025)',
    h1: 'How to Start an Online Business in India — Step by Step',
    description: 'Learn how to start an online business in India in 2025. From picking a profitable idea to your first sale — with AI tools to speed everything up.',
    keywords: ['how to start online business india', 'start online business india', 'online business india beginners'],
    toneHint: 'structured, beginner-friendly, India-specific, AI-forward',
    relatedSlugs: ['how-to-make-first-money-online-india', 'online-business-ideas-india-2025', 'how-to-use-ai-to-start-a-business'],
  },
  {
    category: 'guide',
    slug: 'how-to-stop-overthinking-and-start-building',
    title: 'How to Stop Overthinking and Start Building Your Business',
    h1: 'How to Stop Overthinking and Actually Start Building',
    description: 'Analysis paralysis is the #1 killer of aspiring founders. This guide breaks down why you overthink and gives you a proven framework to start shipping ideas immediately.',
    keywords: ['how to stop overthinking start business', 'analysis paralysis entrepreneur', 'overthinking founder'],
    toneHint: 'empathetic, psychology-aware, direct, action-triggering',
    relatedSlugs: ['aspiring-entrepreneur-guide-india', 'how-to-build-accountability-as-a-founder', 'founder-community-for-beginners'],
  },
  {
    category: 'guide',
    slug: 'how-to-use-ai-to-start-a-business',
    title: 'How to Use AI to Start a Business in India (2025)',
    h1: 'How to Use AI Tools to Start Your Business Faster',
    description: 'AI has made it 10x easier to start a business. Learn exactly which AI tools to use and how to apply them to business ideation, content, outreach, and automation.',
    keywords: ['how to use ai to start business', 'ai for entrepreneurs india', 'ai business tools india 2025'],
    toneHint: 'practical, tool-specific, exciting, accessible to non-tech founders',
    relatedSlugs: ['ai-tools-for-founders-india', 'how-to-find-business-ideas-with-ai', 'best-ai-tools-for-entrepreneurs-2025'],
  },
  {
    category: 'guide',
    slug: 'first-10k-online-india',
    title: 'How to Earn Your First ₹10,000 Online in India (2025)',
    h1: 'Your First ₹10,000 Online: A Real Plan for Indian Founders',
    description: 'Earning your first ₹10,000 online in India is more achievable than you think. This guide covers 5 proven paths with real timelines, tools, and examples.',
    keywords: ['first 10k online india', 'earn first 10000 online india', 'make 10k online india'],
    toneHint: 'specific, milestone-focused, achievable, India rupee amounts',
    relatedSlugs: ['first-10k-challenge-india', 'how-to-make-first-money-online-india', 'online-business-ideas-india-2025'],
  },
  {
    category: 'guide',
    slug: 'how-to-find-business-ideas-with-ai',
    title: 'How to Find Business Ideas Using AI (50+ Ideas Included)',
    h1: 'How to Find Profitable Business Ideas Using AI Tools',
    description: 'Stop waiting for a lightbulb moment. Learn how to use AI tools like ChatGPT, Claude, and Perplexity to uncover business ideas matched to your skills and market.',
    keywords: ['business ideas with ai', 'find business ideas using ai', 'ai business idea generator india'],
    toneHint: 'creative, systematic, tool-driven, idea-generating',
    relatedSlugs: ['online-business-ideas-india-2025', 'how-to-use-ai-to-start-a-business', 'ai-tools-for-founders-india'],
  },
  {
    category: 'guide',
    slug: 'online-business-ideas-india-2025',
    title: '30 Best Online Business Ideas in India for 2025',
    h1: '30 Online Business Ideas in India You Can Start with AI',
    description: 'Looking for online business ideas in India? Here are 30 profitable, AI-friendly business ideas for aspiring founders — with low startup costs and real income potential.',
    keywords: ['online business ideas india 2025', 'business ideas india 2025', 'small business ideas india online'],
    toneHint: 'listicle, India-specific, practical with INR revenue estimates',
    relatedSlugs: ['how-to-find-business-ideas-with-ai', 'how-to-start-online-business-india', 'first-10k-online-india'],
  },
  {
    category: 'guide',
    slug: 'how-to-get-first-client-india',
    title: 'How to Get Your First Client in India (No Experience Needed)',
    h1: 'How to Land Your First Client in India as a First-Time Founder',
    description: 'Getting your first paying client is the hardest step. Learn the exact outreach framework, pricing strategy, and AI tools Indian founders use to close their first deal.',
    keywords: ['how to get first client india', 'get first client freelancing india', 'first client india entrepreneur'],
    toneHint: 'tactical, step-by-step, confidence-building, India-market-aware',
    relatedSlugs: ['how-to-make-first-money-online-india', 'first-10k-online-india', 'ai-tools-for-founders-india'],
  },
  {
    category: 'guide',
    slug: 'how-to-build-accountability-as-a-founder',
    title: 'How to Build Accountability as a Founder (Without a Co-Founder)',
    h1: 'How to Stay Accountable as a Solo Founder',
    description: 'Most founders fail alone. Learn how to build the accountability systems — buddy matching, sprint challenges, and community — that keep you moving toward your goals.',
    keywords: ['founder accountability', 'accountability for solo founders', 'how to stay accountable entrepreneur'],
    toneHint: 'psychological, practical, system-focused, solo founder empathy',
    relatedSlugs: ['accountability-community-for-founders', 'founder-accountability-challenge', 'founder-community-india'],
  },
  {
    category: 'guide',
    slug: 'aspiring-entrepreneur-guide-india',
    title: 'The Complete Guide for Aspiring Entrepreneurs in India (2025)',
    h1: 'The Aspiring Entrepreneur\'s Guide to Starting in India',
    description: 'Everything an aspiring entrepreneur in India needs to know in 2025 — from validating ideas to finding community, using AI tools, and making your first sale.',
    keywords: ['aspiring entrepreneur india', 'guide for entrepreneurs india', 'how to become entrepreneur india'],
    toneHint: 'comprehensive, encouraging, India-focused, journey-based narrative',
    relatedSlugs: ['founder-community-india', 'how-to-start-online-business-india', 'how-to-stop-overthinking-and-start-building'],
  },

  // ── TOOLS ──────────────────────────────────────────────────────────────────
  {
    category: 'tools',
    slug: 'ai-tools-for-founders-india',
    title: 'Best AI Tools for Founders in India (2025)',
    h1: 'The Best AI Tools for Founders in India Right Now',
    description: 'A curated list of the best AI tools Indian founders are using in 2025 to build faster — from content creation to automation, research, and client outreach.',
    keywords: ['ai tools for founders india', 'ai tools entrepreneurs india', 'best ai tools india 2025'],
    toneHint: 'curated, tool-specific, practical with use cases, India-relevant pricing',
    relatedSlugs: ['best-ai-tools-for-entrepreneurs-2025', 'ai-automation-for-small-business-india', 'how-to-use-ai-to-start-a-business'],
  },
  {
    category: 'tools',
    slug: 'ai-tools-for-online-business-india',
    title: 'Top AI Tools for Online Business in India (2025)',
    h1: 'AI Tools That Make Running an Online Business in India Easier',
    description: 'The right AI tools can cut 80% of your manual work. Here are the top AI tools Indian online business owners use for content, sales, customer service, and more.',
    keywords: ['ai tools online business india', 'ai for online business india', 'ai tools ecommerce india'],
    toneHint: 'efficiency-focused, workflow-driven, practical business use cases',
    relatedSlugs: ['ai-tools-for-founders-india', 'ai-automation-for-small-business-india', 'how-to-start-online-business-india'],
  },
  {
    category: 'tools',
    slug: 'ai-tools-for-content-creators-india',
    title: 'Best AI Tools for Content Creators in India (2025)',
    h1: 'AI Tools Every Indian Content Creator Should Be Using',
    description: 'From scripting to editing, thumbnails to SEO — these are the AI tools helping Indian content creators grow faster and monetize smarter in 2025.',
    keywords: ['ai tools content creators india', 'ai for youtube india', 'content creation ai tools india'],
    toneHint: 'creator-focused, platform-specific (YouTube/Instagram), India-market-aware',
    relatedSlugs: ['ai-tools-for-founders-india', 'best-ai-tools-for-entrepreneurs-2025', 'how-to-find-business-ideas-with-ai'],
  },
  {
    category: 'tools',
    slug: 'best-ai-tools-for-entrepreneurs-2025',
    title: 'Best AI Tools for Entrepreneurs in 2025 (Ultimate List)',
    h1: 'The Ultimate AI Tools List for Entrepreneurs in 2025',
    description: 'The definitive guide to AI tools every entrepreneur should know in 2025. Ranked by use case: ideation, marketing, sales, operations, and customer success.',
    keywords: ['best ai tools entrepreneurs 2025', 'ai tools business 2025', 'top ai tools 2025'],
    toneHint: 'authoritative, comprehensive, regularly-updated feel, use-case organized',
    relatedSlugs: ['ai-tools-for-founders-india', 'ai-automation-for-small-business-india', 'how-to-use-ai-to-start-a-business'],
  },
  {
    category: 'tools',
    slug: 'ai-automation-for-small-business-india',
    title: 'AI Automation for Small Business India — Save 10+ Hours/Week',
    h1: 'How Indian Small Businesses Are Using AI Automation to Work Less',
    description: 'Learn how to automate repetitive tasks in your small business using AI — from customer replies to invoicing, social posts, and lead follow-ups. India-focused guide.',
    keywords: ['ai automation small business india', 'business automation ai india', 'automate business india'],
    toneHint: 'time-saving, ROI-focused, practical with specific tool names',
    relatedSlugs: ['ai-tools-for-founders-india', 'ai-tools-for-online-business-india', 'how-to-use-ai-to-start-a-business'],
  },

  // ── CHALLENGE ──────────────────────────────────────────────────────────────
  {
    category: 'challenge',
    slug: '30-day-business-challenge-india',
    title: '30-Day Business Challenge India — Build & Earn in One Month',
    h1: 'Take the 30-Day Business Challenge and Earn Your First Income Online',
    description: 'Join India\'s most intense 30-day business challenge. Pick an idea, build with a cohort, and race to your first ₹10,000 — with daily prompts, accountability, and live leaderboards.',
    keywords: ['30 day business challenge india', 'business challenge india', '30 day startup challenge india'],
    toneHint: 'energetic, gamified, cohort-driven, milestone-focused',
    relatedSlugs: ['first-10k-challenge-india', 'ai-business-challenge-india', 'founder-accountability-challenge'],
  },
  {
    category: 'challenge',
    slug: 'first-10k-challenge-india',
    title: 'First ₹10K Challenge India — Earn ₹10,000 in 30 Days',
    h1: 'The First ₹10K Challenge: Earn ₹10,000 Online in 30 Days',
    description: 'Founders Wing\'s flagship challenge: 30 days, one cohort of founders, one goal — earn your first ₹10,000 online. Daily prompts, live leaderboard, accountability partner included.',
    keywords: ['first 10k challenge india', 'earn 10000 in 30 days india', 'make 10k rupees online challenge'],
    toneHint: 'urgent, specific, gamified, challenge-mindset',
    relatedSlugs: ['30-day-business-challenge-india', 'online-income-challenge-india', 'first-10k-online-india'],
  },
  {
    category: 'challenge',
    slug: 'ai-business-challenge-india',
    title: 'AI Business Challenge India — Build a Business with AI in 30 Days',
    h1: 'The AI Business Challenge: Build Something Real with AI in 30 Days',
    description: 'Can you build a profitable AI-powered business in 30 days? Founders Wing\'s AI business challenge gives you the cohort, tools, and framework to find out.',
    keywords: ['ai business challenge india', 'build business with ai challenge', 'ai startup challenge india'],
    toneHint: 'tech-forward, challenge-oriented, achievable ambition',
    relatedSlugs: ['30-day-business-challenge-india', 'first-10k-challenge-india', 'ai-tools-for-founders-india'],
  },
  {
    category: 'challenge',
    slug: 'online-income-challenge-india',
    title: 'Online Income Challenge India — Make Money Online in 30 Days',
    h1: 'The Online Income Challenge: Your First Rupees from the Internet',
    description: 'Stop dreaming about passive income. This 30-day online income challenge for Indian entrepreneurs gives you a tested system, accountability, and daily action steps.',
    keywords: ['online income challenge india', 'make money online challenge india', 'earn online challenge india'],
    toneHint: 'motivating, realistic, anti-passive-income-hype, India-specific',
    relatedSlugs: ['first-10k-challenge-india', 'how-to-make-first-money-online-india', '30-day-business-challenge-india'],
  },
  {
    category: 'challenge',
    slug: 'founder-accountability-challenge',
    title: 'Founder Accountability Challenge — Build Momentum That Lasts',
    h1: 'The Founder Accountability Challenge: Finally Follow Through on Your Goals',
    description: 'Accountability is the missing ingredient most founders ignore. This challenge pairs you with a buddy, sets weekly goals, and builds the habit of showing up consistently.',
    keywords: ['founder accountability challenge', 'entrepreneur accountability challenge india', 'accountability challenge founders'],
    toneHint: 'habit-forming, introspective, long-term focus, community emphasis',
    relatedSlugs: ['accountability-community-for-founders', 'how-to-build-accountability-as-a-founder', 'founder-community-india'],
  },
]

export function getPageBySlug(category: string, slug: string): SeoPageConfig | undefined {
  return seoPages.find((p) => p.category === category && p.slug === slug)
}
